### ISSUE TITLE
Unexpected Error "... Unable to find taglib ..." when editing repo settings

### ISSUE THREAD

**Issue by mrscotty** [tcplugins/tcDebRepository#18]
From the "Debian Package Repositories" page, clicking on the "edit" action for a debian repo results in the following error page:

Unexpected Error

This was not supposed to happen. Please provide the error details to your TeamCity server maintainer.
If you maintain this TeamCity installation and the request seems legit please report this error to JetBrains.

Error: org.apache.jasper.JasperException: /plugins/tcDebRepository/debRepository/editDebianRepository.jsp (line: [171], column: [4]) Unable to find taglib [myt] for URI: [/plugins/tcDebRepository/debRepository/tag-lib/mytaglib.tld]

Server time: 2017-12-28 09:27:57
TeamCity: 2017.2.1 (build 50732)
Servlet container: Apache Tomcat/8.5.23

Show stacktrace

**Comment by netwolfuk** [comment]
Hi @mrscotty I think this is the same as #16 and #17 
Please check that you are running version 1.0.2 of the plugin, as this contains the fix.
