### ISSUE TITLE
Platform-dependent failures in PluginDataResolverImplTest (Windows)

### ISSUE THREAD

**Issue by unix-junkie** [tcplugins/tcDebRepository#5]
`debrepo.teamcity.entity.helper.PluginDataResolverImplTest` exhibits two test failures when run on _Windows_
 (_Surefire_ report: [debrepo.teamcity.entity.helper.PluginDataResolverImplTest.txt](https://github.com/tcplugins/tcDebRepository/files/651872/debrepo.teamcity.entity.helper.PluginDataResolverImplTest.txt)).

**Comment by netwolfuk** [comment]
Thank you @unix-junkie  for the bug report. I don't have a windows box to test this on, but looking at the surefire report, this should fix it.

**Comment by unix-junkie** [comment]
It does indeed. Thanks for the quick fix!

**Comment by netwolfuk** [comment]
You're welcome. Thanks for reporting it.
